export const ADD_COMMENT = "ADD_COMMENT";
export const TOGGLE_LIKE_FEED = "TOGGLE_LIKE_FEED";

export const FETCH_FEEDS_BEGIN = "FETCH_FEEDS_BEGIN";
export const FETCH_FEEDS_SUCCESS = "FETCH_FEEDS_SUCCESS";
export const FETCH_FEEDS_FAILURE = "FETCH_FEEDS_FAILURE";

export const FETCH_HISTORIES_BEGIN = "FETCH_HISTORIES_BEGIN";
export const FETCH_HISTORIES_SUCCESS = "FETCH_HISTORIES_SUCCESS";
export const FETCH_HISTORIES_FAILURE = "FETCH_HISTORIES_FAILURE";

export const FETCH_PROFILE_INFO_BEGIN = "FETCH_PROFILE_INFO_BEGIN";
export const FETCH_PROFILE_INFO_SUCCESS = "FETCH_PROFILE_INFO_SUCCESS";
export const FETCH_PROFILE_INFO_FAILURE = "FETCH_PROFILE_INFO_FAILURE";
